### ISSUE TITLE
Stuck at Partitioning

### ISSUE THREAD

**Issue by theemutvcode** [cyberos/cyber-installer#3]
I opened the installer and pressed Next. I selected the drive and clicked Next again but i just see the partition menu. The sidebar says Base Packages
_sorry for bad english_

**Comment by omaemae** [comment]
The installer is barely finished. If you want, you can help out by working on the installer!
The base packages menu should trigger the partitioning and installation scripts, possibly from QMLTermWidget. Currently, the base packages menu doesn't exist.

**Comment by omaemae** [comment]
You can find the progress roadmap here: https://github.com/cyberos/cyber-installer/issues/2
